//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zero_Hungers.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public Admin()
        {
            this.Employees = new HashSet<Employee>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public Nullable<int> TotalCollectionRequest { get; set; }
        public int TotalCompletedRequest { get; set; }
        public Nullable<int> CurrentEmployee { get; set; }
        public int Password { get; set; }
    
        public virtual ICollection<Employee> Employees { get; set; }
    }
}
