//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zero_Hungers.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Collection
    {
        public int Id { get; set; }
        public string CollectionStatus { get; set; }
        public int RestaurantId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<System.DateTime> CollectionDate { get; set; }
        public string FoodName { get; set; }
        public string FoodAmount { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Restaurant Restaurant { get; set; }
    }
}
