//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zero_Hungers.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Collections = new HashSet<Collection>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int CollectionRequest { get; set; }
        public string Location { get; set; }
        public int Password { get; set; }
        public Nullable<int> AdminId { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual ICollection<Collection> Collections { get; set; }
    }
}
